const categories = [
  {
    id: 1,
    name: "Lifestyle",
    icon: <Users className="w-5 h-5" />,
    color: "bg-purple-500",
    groups: [
      {
        id: "1",
        name: "Fitness Enthusiasts",
        members: 12847,
        lastActive: "2m ago",
        trending: true,
      },
      { id: "2", name: "Healthy Cooking", members: 8934, lastActive: "5m ago" },
      {
        id: "3",
        name: "Travel Stories",
        members: 15623,
        lastActive: "1h ago",
        verified: true,
      },
      {
        id: "4",
        name: "Minimalist Living",
        members: 6721,
        lastActive: "3h ago",
      },
      {
        id: "5",
        name: "Photography Tips",
        members: 9456,
        lastActive: "45m ago",
      },
    ],
  },
  {
    id: 2,
    name: "Celebrities",
    icon: <Star className="w-5 h-5" />,
    color: "bg-yellow-500",
    groups: [
      {
        id: "6",
        name: "Hollywood Buzz",
        members: 23456,
        lastActive: "1m ago",
        trending: true,
      },
      {
        id: "7",
        name: "Music Artists Fan Club",
        members: 18932,
        lastActive: "3m ago",
        verified: true,
      },
      {
        id: "8",
        name: "Reality TV Discussions",
        members: 11234,
        lastActive: "15m ago",
      },
      {
        id: "9",
        name: "Celebrity Fashion",
        members: 14567,
        lastActive: "22m ago",
      },
      {
        id: "10",
        name: "Award Show Commentary",
        members: 7890,
        lastActive: "1h ago",
      },
    ],
  },
  {
    id: 3,
    name: "Politics",
    icon: <Vote className="w-5 h-5" />,
    color: "bg-blue-500",
    groups: [
      {
        id: "11",
        name: "Global Politics",
        members: 19874,
        lastActive: "4m ago",
        verified: true,
      },
      {
        id: "12",
        name: "Policy Discussions",
        members: 8765,
        lastActive: "12m ago",
      },
      {
        id: "13",
        name: "Election Updates",
        members: 15432,
        lastActive: "8m ago",
        trending: true,
      },
      {
        id: "14",
        name: "Political Theory",
        members: 6543,
        lastActive: "35m ago",
      },
      {
        id: "15",
        name: "Local Government",
        members: 4321,
        lastActive: "2h ago",
      },
    ],
  },
  {
    id: 4,
    name: "Gaming",
    icon: <Gamepad2 className="w-5 h-5" />,
    color: "bg-green-500",
    groups: [
      {
        id: "16",
        name: "RPG Masters",
        members: 31245,
        lastActive: "now",
        trending: true,
      },
      {
        id: "17",
        name: "FPS Arena",
        members: 28976,
        lastActive: "2m ago",
        verified: true,
      },
      {
        id: "18",
        name: "Indie Game Lovers",
        members: 12456,
        lastActive: "7m ago",
      },
      { id: "19", name: "Retro Gaming", members: 9876, lastActive: "18m ago" },
      {
        id: "20",
        name: "Mobile Gaming",
        members: 16543,
        lastActive: "25m ago",
      },
    ],
  },
  {
    id: 5,
    name: "Education",
    icon: <GraduationCap className="w-5 h-5" />,
    color: "bg-indigo-500",
    groups: [
      {
        id: "21",
        name: "Computer Science Hub",
        members: 22134,
        lastActive: "6m ago",
        verified: true,
      },
      {
        id: "22",
        name: "Language Exchange",
        members: 18765,
        lastActive: "9m ago",
        trending: true,
      },
      { id: "23", name: "Study Groups", members: 14532, lastActive: "14m ago" },
      {
        id: "24",
        name: "Online Courses",
        members: 11876,
        lastActive: "28m ago",
      },
      {
        id: "25",
        name: "Academic Research",
        members: 7654,
        lastActive: "1h ago",
      },
    ],
  },
  {
    id: 6,
    name: "Business",
    icon: <Briefcase className="w-5 h-5" />,
    color: "bg-orange-500",
    groups: [
      {
        id: "26",
        name: "Startup Founders",
        members: 16789,
        lastActive: "3m ago",
        verified: true,
      },
      {
        id: "27",
        name: "Marketing Strategies",
        members: 13456,
        lastActive: "11m ago",
      },
      {
        id: "28",
        name: "Freelancers United",
        members: 19234,
        lastActive: "5m ago",
        trending: true,
      },
      {
        id: "29",
        name: "Investment Club",
        members: 8976,
        lastActive: "21m ago",
      },
      {
        id: "30",
        name: "Remote Work Tips",
        members: 12543,
        lastActive: "33m ago",
      },
    ],
  },
];
